### PR TITLE
Feature 2

### PR DESCRIPTION
**Pull request by brtaylor-dev**
This is a request to merge feature-2 into master.

feature-2 included:
- MVC Classes
- Main class
- No Test cases since there's only really a skeleton of the classes at this point.

### CODE REVIEW

**Comment by brtaylor-dev** [comment]
I approve

**Comment by spkaplan** [comment]
Model.java - line40 - "return this.turnCount"
Consistency. 

TextController.java - line 12 - Remove line.
Is there a benefit to reset it to null?

TextView.java - line 15 -  Remove line.
Is there a benefit to reset it to null?

Add the specified .idea/... files to .gitignore

**Comment by brtaylor-dev** [comment]
Made the necessary changes

**Comment by spkaplan** [comment]
I approve.

**Pull request merged**
